POST http://localhost:7123/CreateAccount
Content-Type: application/json

{
    "ID": "younginyoungin",
    "PW": "youngni33",
    "Nickname": "koryasking"
}

###

POST http://localhost:5123/Login
Content-Type: application/json

{
    "ID": "younginyoungin",
    "PW": "youngni33"
}

###
POST http://localhost:5123/CreateAccount
Content-Type: application/json

{
  "ID": "younginyoungin",
  "PW": "youngni33",
  "Nickname": "koryasking"
}