POST http://localhost:5123/Login
Content-Type: application/json

{
    "ID": "younginyoungin",
    "PW": "youngni33"
}

###
POST http://localhost:5123/CreateAccount
Content-Type: application/json

{
  "ID": "younginyoungin",
  "PW": "youngni33",
  "Nickname": "koryasking"
}

###
POST http://localhost:5123/CreateAccount
Content-Type: application/json

{
  "ID": "gksduddls33",
  "PW": "q1w2e3r4t5",
  "Nickname": "GGomaYoungIn"
}


###
POST http://localhost:5123/GetPlayerInventory
Content-Type: application/json

{
  "ID": "younginyoungin",
  "AuthToken": "y3hyw9f0xcaco7o44j6ey0mv3"
}

###
POST http://localhost:5123/GetPlayerInventory
Content-Type: application/json

{
  "ID": "younginyoungin",
  "AuthToken": "6dxqnyb5ohy34hfwglpccanxb"
}
###
POST http://localhost:5123/CreateAccount
Content-Type: application/json

{
  "ID": "kokomong",
  "PW": "1122333",
  "Nickname": "komongkomong"
}
